FROM i386/alpine:3.17@sha256:af6a986619d570c975f9a85b463f4aa866da44c70427e1ead1fd1efdf6150d38 AS build
RUN apk add --no-cache ca-certificates mailcap

FROM scratch

ENTRYPOINT ["/usr/bin/cursecli"]

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /etc/mime.types /etc/

COPY bin/cursecli /usr/bin/cursecli
