FROM i386/alpine:3.16@sha256:46182ff9ace07d20688dc0202a78a4587eaa9c43bc904b13bf44d51a4c831b04 AS build
RUN apk add --no-cache ca-certificates mailcap

FROM scratch

ENTRYPOINT ["/usr/bin/cursecli"]

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /etc/mime.types /etc/

COPY bin/cursecli /usr/bin/cursecli
