FROM arm64v8/alpine:3.16@sha256:ed73e2bee79b3428995b16fce4221fc715a849152f364929cdccdc83db5f3d5c AS build
RUN apk add --no-cache ca-certificates mailcap

FROM scratch

ENTRYPOINT ["/usr/bin/cursecli"]

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /etc/mime.types /etc/

COPY bin/cursecli /usr/bin/cursecli
